workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      java: 17
    triggering:
      events:
        - push
      branch:
        - main
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - 542931338@qq.com
        notify:
          success: true
          failure: true

